### ISSUE TITLE
Clicking on location in an 'Event' loads the wrong location

### ISSUE THREAD

**Issue by HJvanGelder** [KoningJasper/Attendance-Tracker#123]
See provided screenshot. When clicking on "Verzamelen op de boot" google maps opens and instead of showing the boat it shows "Stichting verzameling van Wijngaarden_boot"
![image](https://user-images.githubusercontent.com/4012310/29071519-43956784-7c44-11e7-97d3-fd8c2acf59c6.png)

**Comment by KoningJasper** [comment]
Solve by using a regex to detect if the location of the event includes 'boot', and redirect to 'Nieuwe Havenweg 5, Delft'.

**Comment by HJvanGelder** [comment]
'De Nieuwe Haven 5, Delft' 
Heathen!

**Comment by KoningJasper** [comment]
Fixed in #126
